### ISSUE TITLE
Persistent user session not found

### ISSUE THREAD

**Issue by espensgr** [itpropro/nuxt-oidc-auth#10]
Made a clean install of this repo, added github clientid and client secret.
Ran the `pnpm run dev:prepare` and `pnpm run dev`.
The authentication from github is returned to the same page, but the no user session added.
The console says `[nuxt-oidc-auth]: Persistent user session not found`.
I think this is may be the same problem i'm having with the generic oidc setup from #9?

**Comment by itpropro** [comment]
It sounds like you have still the `session` -> `expirationCheck` turned on. Try turning it off. This only appears, if the provider doesn't return a refresh token and you have `expirationCheck` turned on.

**Comment by espensgr** [comment]
That worked right away!

**Comment by itpropro** [comment]
> That worked right away!

That's great! Just remember that there will be no automatic session refresh possible if you turn `expirationCheck` off. Meaning as soon as the token is expired the user has to login again.

**Comment by espensgr** [comment]
Shouldn't the Github provider have this automatically configured?

**Comment by itpropro** [comment]
> Shouldn't the Github provider have this automatically configured?

If you setup a GitHub App as in the documentation, a refresh token will be provided, that is what the provider is for. I just tested it with this config:

```ts
oidc: {
    defaultProvider: 'github',
    providers: {
        github: {
        redirectUri: 'http://localhost:3000/auth/github/callback',
        clientId: 'CLIENT_ID',
        clientSecret: 'CLIENT_SECRET',
        filterUserinfo: ['login', 'id', 'avatar_url', 'name', 'email'],
        },
    ...
    },
    session: {
      expirationCheck: true,
      automaticRefresh: true,
      expirationThreshold: 3600,
    },
}
```

And it just worked. I get a refresh token, can refresh the session and don't have to turn anything off with the github provider.

**Comment by delta-mind-phofmann** [comment]
I think it is worth mentioning here that scope offline_access is very often (for example with auth0) required in order to receive a refresh token

**Comment by itpropro** [comment]
> I think it is worth mentioning here that scope offline_access is very often (for example with auth0) required in order to receive a refresh token

That would be a good addition to the docs, especially, as the scope **has** to be set by spec at least.
