### ISSUE TITLE
Pre-transform error: [unimport] failed to find "useOidcAuth" imported from "#imports".

### ISSUE THREAD

**Issue by RolandoHidalgo** [itpropro/nuxt-oidc-auth#11]
I get this error (Pre-transform error: [unimport] failed to find "useOidcAuth" imported from "#imports" ) on fresh install of nuxt and this module.
stpes to reproduce:

1.  Install nuxt (pnpm dlx nuxi@latest init test-oidc).
2.  Install this module (pnpm add -D nuxt-oidc-auth).
3. Add  nuxt-oidc-auth to modules in nuxt.config.ts  ( modules: ['nuxt-oidc-auth'])
4. Run nuxt dev.

nuxt.config.ts

```js
export default defineNuxtConfig({
    devtools: {enabled: true},
    modules: [ 'nuxt-oidc-auth']
})
```

package.json
```js
{
  "name": "nuxt-app",
  "private": true,
  "type": "module",
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare"
  },
  "dependencies": {
    "nuxt": "^3.11.1",
    "vue": "^3.4.21",
    "vue-router": "^4.3.0"
  },
  "devDependencies": {
    "nuxt-oidc-auth": "^0.9.11"
  }
}
```
Versions:
- node: v20.9.0
- pnpm: 8.7.6
- window: 21H1 19044.2965

I download the playground and get the same error.

**Comment by itpropro** [comment]
Thanks for your report, I will try to reproduce and fix this asap!

**Comment by itpropro** [comment]
I was not able to reproduce your issue. Here is a minimal Stackblitz reproduction: https://stackblitz.com/edit/nuxt-oidc-auth-repro?file=app.vue
Feel free to reopen the issue with a reproduction on Stackblitz or a repo.

**Comment by RolandoHidalgo** [comment]
since i donwloaded the playgrond and i get the same error, i knew the problem was my config or some version issue. thanks for the quick response. i will try to figure it out.
