### ISSUE TITLE
How is the right way to get user session in the backend?

### ISSUE THREAD

**Issue by hederson** [itpropro/nuxt-oidc-auth#22]
I was wondering how is the right way to get the user session, because I'm planning to use the nuxt as BFF so I need to retrieve the accessToken from the user session.

Is this the right way to get that in the Nitro server?

```
import { requireUserSession, getUserSession } from 'nuxt-oidc-auth/runtime/server/utils/session.mjs'
export default defineEventHandler(async (event) => {
  await requireUserSession(event)
  const session = await getUserSession(event)

  return {
    session,
  }
})
```

**Comment by itpropro** [comment]
Hi,
this is one way of achieving it if you only need it on the server side. Did you already test the code above and did you encounter any issue or things that need improvement?

**Comment by hederson** [comment]
yes, I tested and everything went well so far. I was thinking about the option exposeAccessToken, exposeIdToken and maybe we need something to expose only to the backend. So we may need to create another object to store those only for backend purposes.

What do you think about that?

**Comment by itpropro** [comment]
I didn't have this use case so far, but I think adding a possibility to securely access data from the encrypted persistent session would make sense. `exposeAccessToken` would probably do the job, but we don't want to expose it to the frontend necessarily, if we only need it in the backend.
I added that to the feature backlog, if you have ideas for an implementation, I would be happy to discuss them.

**Comment by gheithen** [comment]
Hello, I have a question concerning getting the user session in the backend. 
I need to use the accesstoken for authorization of my end points.
I have tried doing this

```
export default defineEventHandler(async (event) => {
  const session = await getUserSession(event);
  ...
});

```
But it seems that the accessToken I get here ends up being an old one, if I for instance refresh my page. I can't quite figure out, what the problem is. Do I need to, as @hederson has done, call the 'requireUserSession' before getting my userSession?

**Comment by itpropro** [comment]
Hey @gheithen 
Can you provide some more information like your session configuration? That would help to explain what is available at which point.

**Comment by gheithen** [comment]
yes of course, this is my full config

```
  oidc: {
    defaultProvider: 'oidc',
    providers: {
      oidc: {
        clientId: "jubilaeum_website",
        clientSecret: "xxx",
        responseType: "code",
        authorizationUrl: process.env.NUXT_OIDC_AUTORITY + "/connect/authorize",
        userinfoUrl: process.env.NUXT_OIDC_AUTORITY + "/connect/userInfo",
        redirectUri: process.env.NUXT_PUBLIC_ORIGIN + "/auth/oidc/callback",
        grantType: "authorization_code",
        scope: ["openid", "profile", "offline_access", "email"],
        logoutUrl: process.env.NUXT_OIDC_AUTORITY + "/connect/endsession",
        responseMode: "query",
        tokenUrl: process.env.NUXT_OIDC_AUTORITY + "/connect/token",
        authenticationScheme: "body",
        tokenRequestType: "form-urlencoded",
        exposeAccessToken: true,
        logoutRedirectParameterName: 'ReturnUrl',
      }
    },
    session: {
      expirationCheck: true,
      automaticRefresh: true,
      expirationThreshold: 3600,
    },
    middleware: {
      globalMiddlewareEnabled: false,
      customLoginPage: false,
    },
  },
```

**Comment by itpropro** [comment]
There is only a difference between `requireUserSession` and `getUserSession`, if the token expired in the meantime and no request was made since it expired (which would update the session).
You can directly get the session without calling getUserSession at all with

```
const session = await requireUserSession(event)
```

**Comment by r4id4h** [comment]
If you need to access the accessToken on your server side and you don't want to mess around with the plugin or it's configuration you can just:
`
const sessionId = await getUserSessionId(event);
const persistentSession = await useStorage('oidc').getItem<PersistentSession>(sessionId) as PersistentSession;
const tokenKey = process.env.NUXT_OIDC_TOKEN_KEY as string
const accessToken = await decryptToken(persistentSession.accessToken, tokenKey)
`
