### ISSUE TITLE
Keycloak build entering - 500 

### ISSUE THREAD

**Issue by glennovische** [itpropro/nuxt-oidc-auth#28]
When hardcoding my keycloak config like: 

`"keycloak": {
        "audience": "account",
        "baseUrl": "hardcoded",
        "clientId": "hardcoded",
        "clientSecret": "hardcoded",
        "redirectUri": "hardcoded",
        "exposeAccessToken": true,
      }`

When building and running (`node .output/server/index.mjs`) locally. 
The application starts running and I can authenticate. 

When I want to build it for production so not hardcoding my keys in the nuxt.config like:
`"keycloak": {
        "audience": "account",
        "baseUrl": "",
        "clientId": "",
        "clientSecret": "",
        "redirectUri": "",
        "exposeAccessToken": true,
      }`
      
      then build `npm run build`

ANd then run the application with 
`NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_SECRET='hardcoded' NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_ID='hardcoded' NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL='hardcoded' NUXT_OIDC_PROVIDERS_KEYCLOAK_REDIRECT_URI='hardcoded' node .output/server/index.mjs`

Im getting a 500- Token request failed I have checked my keys 100times also in my bitbucket env keys it should be 100% the same.

**Comment by glennovische** [comment]
Duplicate

**Comment by Trickfilm400** [comment]
Hi @glennovische,

in the other issue you mentioned a workaround for the BASE_URL option:

> On startup replace the keycloak.baseUrl with the NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL

Can you maybe explain what you mean with replace at startup and how this would work? I've also the issue that the baseUrl needs to be present at build time, which is bad, but you seem to have a working workaround? I was unable to fix this, could you give me a hint?

**Comment by glennovische** [comment]
Wow @Trickfilm400 I'm sorry just seeing this comment.

What I did is this made a start.sh with the following code:

`#!/bin/sh
# Remove 'https://' from the environment variable value
CLEAN_URL="${NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL/https:\/\//}"

# Replace [keycloak.baseUrl] with the cleaned URL
sed -i "s|\[keycloak.baseUrl\]|${CLEAN_URL}|g" ./server/chunks/nitro/nitro.mjs

# Start the Node.js server
node ./server/index.mjs`

And via docker run this file so the keyclock.baseUrl is overwritten with the correct url in the nitro.mjs file

**Comment by petitkriket** [comment]
i dont get it, this is missing from the docs, what about 12 factors principles ?  module is barely usable in production, been jumping around for 3 days now this is dauting.
why is the https:// not needed at build time ? The deployement/production part is kind of obscure and undocumented.
