### ISSUE TITLE
Where are session data stored?

### ISSUE THREAD

**Issue by canhnd58** [itpropro/nuxt-oidc-auth#31]
Hi, I am using Docker to deploy my Nuxt app and whenever I restart the Docker container, users are logged out. I guess it is because I have not mounted the directory where session data are stored to a Docker volume.

I have set these variables manually as the doc says:
```
- NUXT_OIDC_SESSION_SECRET
- NUXT_OIDC_TOKEN_KEY
- NUXT_OIDC_AUTH_SESSION_SECRET
```

**Comment by NikoHadouken** [comment]
This plugin is using the storage api from nuxt for session data.
By default an in memory adapter is used but you can configure an alternative like filesystem or redis in your `nuxt.config.ts` file.

```ts

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ["nuxt-oidc-auth"],
  oidc: {
    // ...
  },
  nitro: {
    storage: {
      oidc: {
        // example filesystem
        driver: 'fs',
        base: './var/sessions',

        // example redis
        // driver: 'redis',
        // base: 'oidc',
        // url: 'redis://127.0.0.1:6379/2',
      }
    }
  }
})
```

**Comment by itpropro** [comment]
The module is using the unstorage instance of nitro. You can configure it in the nuxt config like this:

```
  nitro: {
    storage: {
      oidc: {
        driver: 'fs',
        base: 'playground/oidcstorage'
      }
    }
```

You can also find the example in the playground folder. I would recommend using something like redis, the session itself (data) is also encrypted.
