### ISSUE TITLE
Session showing as being logged in even when the token is expired

### ISSUE THREAD

**Issue by victorlmneves** [itpropro/nuxt-oidc-auth#33]
Hi
First of all thanks for your work
Currently, I'm evaluating the package as an alternative to `nuxt-auth-utils` because I need the `refreshToken` functionality that is not yet available on that lib
I have clone the repo and from what I saw the auth is set as a global middleware so I have duplicated the index page just to check how it behaves when navigating between pages
I have console the `loggedIn` and user object and the loggedIn always returns as true and the user `expireAt` returns a date that shows that it has expired compared to the current time as visible on the screenshot

![image](https://github.com/itpropro/nuxt-oidc-auth/assets/17341789/026fbd0f-6e33-4679-bce0-083de43f7c8a)

Thanks

**Comment by itpropro** [comment]
According to your screenshot, you have logged in at "Wed May 15 2024 07:54:58 GMT+0000" (1715759698) and `expireAt` is set to "Wed May 15 2024 08:24:57 GMT+0000" (1715761497).
That means that your token is valid for 30 minutes.
