### ISSUE TITLE
Which name should we use as middleware when not using global middleware option

### ISSUE THREAD

**Issue by victorlmneves** [itpropro/nuxt-oidc-auth#34]
Hi
I have set the globalMiddlewareEnabled as false as I want to define manually which pages are protected.
Doing this, which is the right name to use as middleware?

I have tried '00-oidc-auth', but it doesn't work

```
definePageMeta({
    middleware: ['00-oidc-auth']
})
```

Thanks

**Comment by gheithen** [comment]
@victorlmneves it doesn't really matter. I've made a custom middleware, and called it something with auth, where I utilize the useOidcAuth composable

**Comment by victorlmneves** [comment]
thanks @gheithen

**Comment by itpropro** [comment]
The naming is only important for the order, middlewares are loaded. If you use your own, it doesn't matter from a functionality perspective, as @gheithen mentioned.
If you want to know more about middleware ordering, check this chapter in the Nuxt docs: https://nuxt.com/docs/guide/directory-structure/middleware#ordering-global-middleware
