### ISSUE TITLE
Can't access requireUserSession()

### ISSUE THREAD

**Issue by victorlmneves** [itpropro/nuxt-oidc-auth#35]
Hi

I'm trying to replace `nuxt-auth-utils` with this lib mainly because of the `refreshToken` functionality and I have a server endpoint where I need to access the session to extract some of the data to be able to authenticate on another app

I see that the function exists, on the repo code, but I get the message that is not defined

How can I manage this?

Thanks

**Comment by gheithen** [comment]
Hi @victorlmneves, how have you made the import?
Mine looks like this, and it works:
`import {
  getUserSession,
  requireUserSession,
} from "nuxt-oidc-auth/runtime/server/utils/session.mjs";`
