### ISSUE TITLE
WSO2 Identity Provider implementation

### ISSUE THREAD

**Issue by Everr23** [itpropro/nuxt-oidc-auth#37]
Hi, I'm trying to implement this module with WSO2 Identity Provider 7.0.0.
I have the problem that the user is stuck in an endless redirection loop between the application and WSO2, it seems that the session is not recognized.

The WSO2 login opens correctly, when logging in it redirects back to the callback but as the application does not recognize the session it redirects to the WSO2 login. I have not been able to identify the error yet. I also do not know if my implementation of the module is correct, the callback url must have a specific format? Or is any additional configuration needed?

This is my configuration in `nuxt.config.ts`:

```ts
{
  //...
  oidc: {
    enabled: true,
    defaultProvider: "oidc",
    providers: {
    oidc: {
    clientId: "xxx",
    clientSecret: "xxx",
  
    /* Url configurations*/
    redirectUri: "http://localhost:8080/",
    // I also tried with: "http://localhost:8080/auth/oidc/login",
    
    tokenUrl: "https://localhost:9443/oauth2/token",
    authorizationUrl: "https://localhost:9443/oauth2/authorize",
    userinfoUrl: "https://localhost:9443/oauth2/userinfo",
    
    scope: ["openid", "profile"],
    
    /* Other possible configurations I saw, I tried some combinations */
    // responseType: "",
    // responseType: "",
    // responseMode: "",
    // responseMode: "",
    // grantType: "",
    // authenticationScheme: "",
    // tokenRequestType: "",
    },
    },
    middleware: {
      /* If true loop bug happens*/
      globalMiddlewareEnabled: false,
      customLoginPage: false,
    },
    provideDefaultSecrets: true,
  },
}
```

Back to the callback the url brings with it information about the session
![image](https://github.com/itpropro/nuxt-oidc-auth/assets/56978959/9e15812c-15a3-420f-bfcc-558c413868c4)

You can see here the cookies
![image](https://github.com/itpropro/nuxt-oidc-auth/assets/56978959/9be0a5c2-da02-4292-9890-f52db497d9b7)

I also have to admit that I am a junior developer, so I might be overlooking some necessary configuration in the WSO2 Identity Provider.

Thanks in advance for the help

**Comment by agracia-foticos** [comment]
please i want to implement it with WSO2 :) thanks in advance

**Comment by Everr23** [comment]
> please i want to implement it with WSO2 :) thanks in advance

Hi @agracia-foticos , I implemented SSO with WSO2 using [@asgardeo/auth-spa](https://www.npmjs.com/package/@asgardeo/auth-spa)

**Comment by Everr23** [comment]
> please i want to implement it with WSO2 :) thanks in advance

Hi, I implemented WSO2 in Nuxt whit [@asgardeo/auth-spa](https://www.npmjs.com/package/@asgardeo/auth-spal)

In order to make the package work I had to create a plugin that load only on the client side

The plugin looks like:
```
import { defineNuxtPlugin } from "#app";
import { AsgardeoSPAClient, Hooks } from "@asgardeo/auth-spa";

export default defineNuxtPlugin((nuxtApp) => {
  const auth = AsgardeoSPAClient.getInstance();

  auth?.initialize({
    signInRedirectURL: "xxx",
    signOutRedirectURL: "xxx",
    clientID: "xxx",
    baseUrl: "xxx",
    scope: ["openid", "profile", "email"],
  });

  auth?.signIn();

  auth?.on(Hooks.SignIn, (response) => {
    console.log("You have successfully signed in!", response);
  });

  // Plugin Injections: provide access to the auth data via helpers
  return {
    provide: {
      signOut: async () => {
        auth?.signOut();
      },
      isAuthenticated: async () => {
        return await auth?.isAuthenticated();
      },
      authData: async () => {
        return await auth?.getBasicUserInfo();
      },
      decodedIDToken: async () => {
        return await auth?.getDecodedIDToken();
      },
      accessToken: async () => {
        return await auth?.getAccessToken();
      },
      OIDCServiceEndpoints: async () => {
        return await auth?.getOIDCServiceEndpoints();
      },
    },
  };
});
```

To use in your vue files:

`const { $isAuthenticated, $authData } = useNuxtApp();`

**Comment by agracia-foticos** [comment]
@Everr23  we have our own WSO2 server

**Comment by itpropro** [comment]
@Everr23 auth-spa has a very different focus than this package. We do not support SPA with this module, as secure authentication is only possible with a server component. You can have flows (with packages like auth-spa) that work on an SPA, but a server side component to auth is always considered more secure.
Could it be that you are not running Nuxt with SSR? (`ssr: true`)
