### ISSUE TITLE
Unable to retrieve ID token for Keycloak id_token_hint logout

### ISSUE THREAD

**Issue by Degoya-Studio** [itpropro/nuxt-oidc-auth#40]
Hi, I'm encountering difficulties obtaining a valid ID token that I would like to use for Keycloak logout. The ID token is not included in the user object, and attempting to set `exposeIdToken: true` in the provider configuration results in an infinite loop after login.

Current configuration:

```javascript
oidc: {
  defaultProvider: 'keycloak',
  providers: {
    keycloak: {
      audience: 'account',
      baseUrl: 'http://localhost:8080/realms/dzg',
      redirectUri: 'http://localhost:3000/auth/keycloak/callback',
      clientId: 'xx',
      clientSecret: 'xx',
      authorizationUrl: 'http://localhost:8080/realms/dzg/protocol/openid-connect/auth',
      tokenUrl: 'http://localhost:8080/realms/dzg/protocol/openid-connect/token',
      logoutUrl: 'http://localhost:8080/realms/dzg/protocol/openid-connect/logout',
      logoutRedirectParameterName: 'post_logout_redirect_uri',
      scope: ['openid', 'profile', 'email'],
      responseType: 'code',
      exposeAccessToken: true,
      grantType: 'authorization_code'
    }
  },
  middleware: {
    globalMiddlewareEnabled: true,
    customLoginPage: false
  }
}

**Comment by Mattymoo007** [comment]
@Degoya-Studio did you manage to find a way to get the `idToken` value somehow? Im struggling with the same situation. I want to logout the user (end session) without the logout confirmation screen. Ive searched all around and indeed you need to provide `id_token_hint` with `post_logout_redirect_uri` parameter to get this behaviour from keycloak. Ive tried a number of things to try and get the idToken but no luck so far. 

When I add `exposeIdToken: true` to my config I dont get infinite redirecting behaviour but I do get:
```
Set-Cookie header is ignored in response from url: https://localhost:3000/auth/keycloak/callback. The combined size of the name and value must be less than or equal to 4096 characters.
```
I assume the logic breaks here and no `userInfo` is passed `nuxt-oidc-auth` module because the `user` data is null. Perhaps this could be the issue? Thanks for your time 🍻

My configuration:
```js
oidc: {
    providers: {
      keycloak: {
        baseUrl: process.env.NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL || '',
        clientId: process.env.NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_ID || '',
        clientSecret: process.env.NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_SECRET || '',
        redirectUri: process.env.BASE_URL + '/auth/keycloak/callback',
        logoutUrl: process.env.NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL + '/protocol/openid-connect/logout',
        logoutRedirectParameterName: `client_id=${process.env.NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_ID}&post_logout_redirect_uri`,
        tokenUrl: process.env.NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL +'/protocol/openid-connect/token',
        pkce: true,
        grantType: 'authorization_code',
        exposeAccessToken: true,
        tokenRequestType: 'form-urlencoded',
        responseType: 'code id_token',
        nonce: true,
        scopeInTokenRequest: true,
        scope: ['openid'],
      },
    },
    middleware: {
      globalMiddlewareEnabled: false,
    },
  },
```

**Comment by Degoya-Studio** [comment]
@Mattymoo007 I switched to [nuxt-auth-utils](https://github.com/Atinux/nuxt-auth-utils) and there it worked fine for me. I think you're getting this issue, because the library can't store id_token plus the other tokens you're using in the cookies. You need to somehow only save the id_token without refresh and access token, I reckon.

**Comment by itpropro** [comment]
> @Mattymoo007 I switched to [nuxt-auth-utils](https://github.com/Atinux/nuxt-auth-utils) and there it worked fine for me. I think you're getting this issue, because the library can't store id_token plus the other tokens you're using in the cookies. You need to somehow only save the id_token without refresh and access token, I reckon.

This is a general problem of cookies/h3 and would impact nuxt-auth-utils in the same way if they would expose id or access token via the session.
A general problem with Keycloak is that is promotes a lot of bad practices towards JWT usage such as storing non-essential user data in tokens instead of using the tokens for auth only and then requesting additonal user information from a db/service/userendpoint etc..

Try to not use `exposeAccessToken` or `exposeIdToken` at all and try to reduce the load of these on Keycloak side. If you absolutely need one of them try to only expose that one.

**Comment by mrleblanc101** [comment]
@Degoya-Studio How did you make that work ? [nuxt-auth-utils](https://github.com/Atinux/nuxt-auth-utils) is very bare bone and only found the clear method which only logout in the Nuxt app

**Comment by itpropro** [comment]
> I've got the same issue with Keycloak 25.
> 
> ![Screenshot 2024-09-13 at 10 44 32 AM](https://private-user-images.githubusercontent.com/17392251/367340499-eb72336d-5255-46e8-9ad4-c4cf6b541517.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMzYyNzYsIm5iZiI6MTcyNzEzNTk3NiwicGF0aCI6Ii8xNzM5MjI1MS8zNjczNDA0OTktZWI3MjMzNmQtNTI1NS00NmU4LTlhZDQtYzRjZjZiNTQxNTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDIzNTkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNjU1YmExMWNkZjhhNmM1Y2FlNjBjZWQ2MTc2ZjhkM2U4ZTNhNGE2NGJhYzk4NDFlYjU4MjI0NjM1YTgxNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dizxTbvd8GcDqqlMfXIfRjJtl2zgP1zGGtDi1mnAL6A)
> 
> @Degoya-Studio How did you make that work with [nuxt-auth-utils](https://github.com/Atinux/nuxt-auth-utils) ? It's very bare bone and only found the clear method which only logout in the Nuxt app

@Degoya-Studio it is not possible with `nuxt-auth-utils` currently, you can only leave out the post redirect uri completely. That is how they handled it, there is simply no `logoutUrl` option at all.
With the current version v0.16.0, there is a cognito provider, as well as the capability to add custom fields to auth, token and logout requests.
The provider preset for cognito will handle the two required parameters `client_id` and `logout_uri`. Don't forget to specify `logoutRedirectUri` in the provider options and to add that specific url to your cognito configuration in the AWS portal.

**Comment by VictorioBerra** [comment]
@itpropro I think I am missing something super simple, but I have this module working in my SSR Nuxt3 app against KeyCloak.

I have a logged-in user now and userInfo populated.

Finally, I want to call my API which is protected by KeyCloak. I need my access token to make an API call.

How do I get the access token to attach to my authorization header and make that call?

**Comment by itpropro** [comment]
> @itpropro I think I am missing something super simple, but I have this module working in my SSR Nuxt3 app against KeyCloak.
> 
> I have a logged-in user now and userInfo populated.
> 
> Finally, I want to call my API which is protected by KeyCloak. I need my access token to make an API call.
> 
> How do I get the access token to attach to my authorization header and make that call?

Hey,
you can use the exposeAccessToken parameter to expose the access token though the user session. From a OIDC standpoint you should make sure that the audience of the token is the id of your api. To have a correct access token for your API, the aud field has to match the one of the registration of your API, otherwise you will not be able to correctly validate it inside your API handlers.

**Comment by VictorioBerra** [comment]
@itpropro  I added more info to my orig comment. Those flags do nothing in my config.

**Comment by mrleblanc101** [comment]
@VictorioBerra It does work, here is what I have on my side:
```
export default defineNitroPlugin(() => {
    sessionHooks.hook('fetch', async (session) => {
        console.log('session', session);
        if (!(Object.keys(session).length === 0)) {
            const profileResponse = await $fetch('http://api.campus-eeq.local.vici.io/api/users/me', {
                method: 'GET',
                headers: {
                    Accept: 'application/json',
                    Authorization: `Bearer ${session.accessToken}`,
                },
            });

            session.entrepreneur = profileResponse.data.entrepreneur;
        }
    });
});
```

**Comment by VictorioBerra** [comment]
@mrleblanc101 Is there anything wrong with my config, or my button click event?

![image](https://github.com/user-attachments/assets/a0563772-10a7-4788-8da6-235eaace8103)

**Comment by mrleblanc101** [comment]
@VictorioBerra Not that I see, maybe the token is only exposed on the server side.
As you can see, my console.log is in the nitro plugin `fetch` hook, so I can pull the the profile before login in the user.

**Comment by VictorioBerra** [comment]
Same result with:

@mrleblanc101 

```ts
    const { fetch } = useOidcAuth()
    fetch()
        .then(data => {
            console.log(data)
        })
        .catch(error => {
            console.error('Error:', error)
        })
```

Which I confirm hits /api/_auth/session **server side** so I assume tokens would be returned and they are not. Is that supposed to work?

**Comment by mrleblanc101** [comment]
@VictorioBerra I doubt you are using the latest version.
Also, the sessionHooks should be in `server/api/auth/session.ts`

**Comment by VictorioBerra** [comment]
@mrleblanc101 package.json `"nuxt-oidc-auth": "^0.18.0",`.

Not sure I follow on the hooks, the above code I showed `fetch()` hits `api/_auth/session`

**Comment by itpropro** [comment]
> @mrleblanc101 Is there anything wrong with my config, or my button click event?
> 
> ![image](https://private-user-images.githubusercontent.com/2934507/373406912-a0563772-10a7-4788-8da6-235eaace8103.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5OTE5MjEsIm5iZiI6MTcyNzk5MTYyMSwicGF0aCI6Ii8yOTM0NTA3LzM3MzQwNjkxMi1hMDU2Mzc3Mi0xMGE3LTQ3ODgtOGRhNi0yMzVlYWFjZTgxMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMjE0MDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDQyYmNlODY4MTQyOWRhNTcyZDQyZTEwYTQ1YzBjM2E3ZjE5YTU4YWJmNDJhZWIwYjQ2ZWJkMzBlZjBiMTUxMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.HHe5qeW8E11okxH9wYjaSQJ-OzBo2TkE1FWyThfV2Nk)

In addition to what @mrleblanc101 already stated, you should try to avoid using process.env in your Nuxt config.
The first reason is that you should in general only use import.meta.env and the main one is that you should load variables from the environment in the documented way by using NUXT env variables:

```
NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_SECRET=YOUR_SECRET
NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_ID=YOUR_ID
NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL=KEYCLOAK_HOST/realms/YOUR_REALM
```

**Comment by mrleblanc101** [comment]
@VictorioBerra Did you logout and login again ?
If you just refresh it work work I think.

@itpropro I've never heard of not using `process.env`, I use it all the time and that's what they use in the Nuxt doc:
https://nuxt.com/docs/api/composables/use-runtime-config#define-runtime-config
What's the difference with `import.meta.env` ?

**Comment by itpropro** [comment]
> @VictorioBerra Did you logout and login again ? If you just refresh it work work I think.
> 
> @itpropro I've never heard of not using `process.env`, I use it all the time and that's what they use in the Nuxt doc: https://nuxt.com/docs/api/composables/use-runtime-config#define-runtime-config What's the difference with `import.meta.env` ?

There is no strict don't use, but linters for example have already started to pick this up as recommended. The Nuxt team also recommends it, you can read more about that here (and you will find it in many places across the ecosystem already) https://nuxt.com/docs/api/advanced/import-meta.

Especially for determining, if you are on client or browser and in which node environment you are it is recommended to use `import.meta.client` or `import.meta.dev` respectively.

For security reasons, you should not directly load from process.env in you nuxt.config, as that bypasses the mechanisms of config merging that requires you to "allow" a value by defining it in your config as empty string, which will then get merged if it has the `NUXT` or `NITRO` prefix if you are only using Nitro.

In addition for better DX, I recommend using T3 Env https://env.t3.gg/docs/nuxt

**Comment by VictorioBerra** [comment]
GOT IT. KeyCloak by default sets the access token expiration to 1 minute. Once I bumped to 1 hour, it all started working. That was frustrating.

**Comment by itpropro** [comment]
> GOT IT. KeyCloak by default sets the access token expiration to 1 minute. Once I bumped to 1 hour, it all started working. That was frustrating.

Yeah, Keycloak has a lot of weird defaults :D Glad you found that!

**Comment by nettnikl** [comment]
If anyone is still experiencing this issue - could you check if my changes from the linked issue above fixes the issue for you?
