### ISSUE TITLE
Consider allowing user to augment UserSession typescript definition

### ISSUE THREAD

**Issue by nathanbrizzee-cdcr** [itpropro/nuxt-oidc-auth#41]
Currently, if you use the `sessionHook.hook("fetch")` Nitro Plugin to modify the User session object, you get Typescript warnings that the fields you added don't exist on the UserSession.  The same issue was solved on the `nuxt-auth-utils` project by moving the UserSession interface inside a declare module section and allowing the user to augment the interface.

See the following commits:
https://github.com/Atinux/nuxt-auth-utils/pull/2/commits/b3e92c8862fb582d32fe7eff9b6d87601f622ee9
https://github.com/Atinux/nuxt-auth-utils/pull/2/commits/3c762e4a96db168acb335f800db0dfa0fac8c36e

I was able to get it to work with this hack.
```js
// auth.d.ts
import "nuxt-oidc-auth/runtime/types/session.js";
declare module "nuxt-oidc-auth/runtime/types/session.js" {
  interface UserSession {
    // Add your own fields to extend the interface
    roles?: String[];
    clientid?: string;
    nonce: string;
  }
}
export {};
```

It would be nice to do it similar to the way the `nuxt-auth-utils` project does it:
https://github.com/Atinux/nuxt-auth-utils?tab=readme-ov-file#session-management

```js
// auth.d.ts
declare module "#auth-utils" {
  interface User {
    // Add your own fields
    userid: string;
    fullname: string;
    username: string;
    locale: string;
    firstname: string;
    lastname: string;
    email: string;
  }

  interface UserSession {
    // Add your own fields
    user: User;
    roles?: String[];
    clientid?: string;
    nonce: string;
  }
}

export {};
```

**Comment by itpropro** [comment]
Thanks for your feedback!
It was actually expandable at the start but for better compliance to the OIDC standard and to have a common object, this was removed. What case do you have that requires extending, where it cannot use the `claims` or the `providerInfo` property?

**Comment by itpropro** [comment]
I think #21 would satisfy your request. Feel free to open a new issue if that is not enough.

**Comment by nathanbrizzee-cdcr** [comment]
> Thanks for your feedback! It was actually expandable at the start but for better compliance to the OIDC standard and to have a common object, this was removed. What case do you have that requires extending, where it cannot use the `claims` or the `providerInfo` property?

Thanks.  For my application, I am trying to add some additional pieces of information that do not come from the IDP.  I have some roles that have to be looked up from a different system.  Putting these additional roles in the session makes it so much easier for both the front end and the back end to access and not have to make calls to the 3rd party database.  That was my reason for augmenting the session.

**Comment by nathanbrizzee-cdcr** [comment]
> I think #21 would satisfy your request. Feel free to open a new issue if that is not enough.

Hmm, let me look into this a little more.  I didn't try it this way.  Thanks!

**Comment by mrleblanc101** [comment]
I our case, we get the User from Keycloak, but most of the user property (aka profile) comes from our Laraval backend

**Comment by mrleblanc101** [comment]
It's annoying, I would have to do `user.providerInfo.entrepreneur` instead of `user.entrepreneur`.
I don't even understand why all the data is not at the root level

**Comment by nathanbrizzee-cdcr** [comment]
> It's annoying, I would have to do `user.providerInfo.entrepreneur` instead of `user.entrepreneur`. I don't even understand why all the data is not at the root level

That's how I originally had my code @mrleblanc101  and I had to refactor it all to use user.providerInfo.xxxx .  It was more annoying to have to add the providerInfo in there.  If you use my auth.d.ts from above, you can use fields directly on the UserSession for the shorter case. I wanted to be compliant with the recommendations of the library so in case it changes later on, it doesn't totally break my code.

**Comment by itpropro** [comment]
> It's annoying, I would have to do `user.providerInfo.entrepreneur` instead of `user.entrepreneur`. I don't even understand why all the data is not at the root level

I understand your concern here, but the focus is on compliance with oidc and it is formally the providerinfo.
The user object itself should represent the federated identity in the context of the the oidc flow, where any user information not necessary for auth should be coming from the userinfo endpoint or a separate service.
Although I want to keep it this way, because it’s mapped to the way oauth is structured, I will add a feature to the backlog for a flattened user object in case that is preferred.

**Comment by mrleblanc101** [comment]
Thank you,
We are currently using Nuxt 2 and `@nuxtjs/auth-next` with Keycloak and our user and profile is flattenen
