### ISSUE TITLE
How to protect global routes and api routes

### ISSUE THREAD

**Issue by HoldenMalinchock** [itpropro/nuxt-oidc-auth#42]
I am trying to require authentication to my server/api routes but I am having a hard time making middleware work for both pages and /server.  I want to support outside api calls to /api with a user/pass or token.  While the website must have oidc auth to every page.

I have global middleware enabled so every page is redirected to my OIDC auth which is great but anyone can just go to /api/users no session needed.  If I make a global server middleware to visit /api routes and check for a session and if no session then check for auth token it works from an outside request.  However it doesn't work when visiting the website with no session.  Trying to visit localhost:3000/ fails because the page requests /api/user info and server middleware returns a 401 and the oidc redirect doesn't happen. 

How do I handle this.  I want to allow api endpoints to check for a token but it seems any blocks on those routes prevents the globalMiddleware from executing.  I am sure I am missing something but not sure what to do.

**Comment by itpropro** [comment]
On the server side you have access to the server session with 

```
export default eventHandler(async (event) => {
  const session = await requireUserSession(event)
})
```

But keep in mind that the tokens coming from oidc auth should not be used for your own API auth, as the audience is the app, not your API. 
I would use a nitro middleware and run a completely different set of auth checks on your API, validating user/pass and or an accessToken with mechanics proper to API auth, making it independent of the NuxtRoute middleware, which should only apply to actual websites.
