### ISSUE TITLE
Allow storing the session even without refresh_token

### ISSUE THREAD

**Issue by Xa3lis** [itpropro/nuxt-oidc-auth#43]
Hello !

I'm trying to use this plugin to handle auth with PingID, it's working pretty well but I just have a problem

Our app is deployed on GKE and there is an auto pod scaling, so sometimes the app is running on 2 or 3 pods at the same time

We need our session to be stored on a `Redis`, but in our company the `refresh_token` is disabled by default and we need a "good reason" to enable it

I digged into the code a bit, and I saw the save of the session using nitro storage is only made when `refresh_token` is present

Is there a way to make the session persistent even without `refresh_token` ? Because right now it's the only thing that's disallow us to use this library

Thank's !

**Comment by itpropro** [comment]
Hey,
Thanks for you feedback! Currently it is not possible to store the normal session in a remote location, afaik there is no option in h3 to support that.
I am working on an update to make it possible to make persistent session independent of a refresh_token, that will probably solve your problem, but I can unfortunately not work on that before next week.

**Comment by itpropro** [comment]
The current implementation makes it possible to store the persistent session at any supported unstorage location. If you have a proper load balancer/gateway in place that tranparently distributes user across nodes while preserving headers etc., the persistent session should be discoverable from any node running the same website.
