### ISSUE TITLE
Token Request Failed - Callback route not found

### ISSUE THREAD

**Issue by mmillican** [itpropro/nuxt-oidc-auth#45]
I am having an issue getting this to run in my Nuxt project using the generic OIDC provider (with AWS Cognito).

The auth flow initializes fine and I get to the Cognito login page fine. When redirected back to the callback page, I get a `500: Token request failed` error. Looking at the console logs, I see that its failing to find the route for the callback, even though I have the middleware registered. I have compared everything else I can think of to the playground project in the repository.

```
[nuxt] error caught during app initialization Error: Page not found: /auth/oidc/callback?
```

**Package versions:**
Nuxi: ^3.12.0
Nuxt: ^3.12.4
nuxt-oidc-auth: ^0.12.0

Nuxt.config.ts

```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default {
	modules: [
    "nuxt-oidc-auth",
  ],
	googleFonts: {
		families: {
			Inter: true,
		},
	},
	tailwindcss: {
		jit: true,
	},
  runtimeConfig: {
    public: {
      apiBaseUrl: process.env.API_BASE_URL,
    },
  },
  imports: {
    dirs: ['./utils'],
  },
  oidc: {
    middleware: {
      globalMiddlewareEnabled: true,
    },
    defaultProvider: 'oidc',
    providers: {
      oidc: {
        clientId: '***',
        clientSecret: '***',
        responseType: 'code',
        pkce: true,
        authorizationUrl: 'https://***.auth.us-east-1.amazoncognito.com/oauth2/authorize',
        tokenUrl: 'https://***.auth.us-east-1.amazoncognito.com/oauth2/token',
        userinfoUrl: 'https://***.auth.us-east-1.amazoncognito.com/oauth2/userInfo',
        redirectUri: 'http://localhost:3000/auth/oidc/callback',
        scope: [ 'openid', 'profile' ],
        responseMode: 'query',
      },
    },
  },
  nitro: {
    preset: 'node-server',
    storage: { // Local file system storage for demo purposes
      oidc: {
        driver: 'fs',
        base: 'oidcstorage'
      }
    }
  },
};
```

**Comment by DiogoCunhaMoreira** [comment]
If meanwhile you solve this issue please tell us how. I'm also with the same problem and cant figure it out.

Thanks a lot.

**Comment by MartinVogtFHNW** [comment]
I have the same problem here and would appreciate a solution. The redirect to the IdP and back to the app with the auth code work. But afterwards, it is displayed that the route cannot be found.

<img width="704" alt="image" src="https://github.com/user-attachments/assets/fd102f93-77e3-4296-be90-bd18b1b67c06">

![image](https://github.com/user-attachments/assets/926d2767-56e5-47e4-a7bc-2603e2a1ba56)

**Comment by DiogoCunhaMoreira** [comment]
I'm still with the same issue but i find out that the code_verifier is not being sent when doing the token request with the access token. Do you also have the same issue? With postman i have the bad request error not 500 but this is also a issue i think. I try to console log the code_verifier but i get undifined.

**Comment by itpropro** [comment]
@mmillican have you configured the callback url correctly in AWS?
I recently tried the generic OIDC provider with AWS Cognito and that worked fine, would you mind sharing your cognito config?

**Comment by itpropro** [comment]
> I have the same problem here and would appreciate a solution. The redirect to the IdP and back to the app with the auth code work. But afterwards, it is displayed that the route cannot be found.
> 
> <img alt="image" width="704" src="https://private-user-images.githubusercontent.com/113760890/355385770-fd102f93-77e3-4296-be90-bd18b1b67c06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4ODk4NDYsIm5iZiI6MTcyNDg4OTU0NiwicGF0aCI6Ii8xMTM3NjA4OTAvMzU1Mzg1NzcwLWZkMTAyZjkzLTc3ZTMtNDI5Ni1iZTkwLWJkMThiMWI2N2MwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQyMzU5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjE2NDQxM2I4MTlkYjQ2MDBlMzY5ZDYzMTBlYmVhNjEyODAzZWNjOTMzMmM1MmM4M2M5OTdhNDQ0MzgzNjg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OZWfCq6d7DmxkNNIy6TJ_pvHcJ53D-3TltJYrdcBLIs">
> ![image](https://private-user-images.githubusercontent.com/113760890/355384845-926d2767-56e5-47e4-a7bc-2603e2a1ba56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4ODk4NDYsIm5iZiI6MTcyNDg4OTU0NiwicGF0aCI6Ii8xMTM3NjA4OTAvMzU1Mzg0ODQ1LTkyNmQyNzY3LTU2ZTUtNDdlNC1hN2JjLTI2MDNlMmExYmE1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOFQyMzU5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNjllZTkwNmMyMjFlMTdjODk1YjkyY2UxMGMyMDk2MDNiMzg4MjIyYWNjNTY5NzlhZDdhNDQzOGJiMDgyN2RkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.y3ybEiPDXMiJEa8tIYs_XzRAeL28P6CWDdoM5VmgGhw)

This is just a warning by the Nuxt router, but shouldn't have any impact on the actual functionality. In version 0.12.1 there was a visual fix to get rid of that warning.
Would be interesting what the actual request error for the token request on the console is.

**Comment by itpropro** [comment]
> If meanwhile you solve this issue please tell us how. I'm also with the same problem and cant figure it out.
> 
> Thanks a lot.

Would you mind open a separate issue for the OIDC provider you are trying it with and some details?

**Comment by DiogoCunhaMoreira** [comment]
> > If meanwhile you solve this issue please tell us how. I'm also with the same problem and cant figure it out.
> > Thanks a lot.
> 
> Would you mind open a separate issue for the OIDC provider you are trying it with and some details?

Hey itpropro, thanks for answering. I have opened a issue talking about this and i found a solution, still having problems but at least the 500 dissappeard. You can check it:
Title:
Token request failed - [nuxt-oidc-auth]: [POST] "https://github.com/login/oauth/access_token": <no response> fetch failed

Thanks a lot

**Comment by mmillican** [comment]
@itpropro sorry for the delay. Here's a screenshot of the relevant config for the callback:

![image](https://github.com/user-attachments/assets/39cc6f79-3548-43ac-ae2f-49880ef381b0)

**Comment by the-tmp** [comment]
Hello everyone,

I just got started with nuxt and the nuxt-oidc-auth module and I am stuck on the same issue. I just tried a basic setup (IdP Zitadel) and everything works fine untill the browser comes back with the callback call from the IdP. I don't think this is an IdP issue as nuxt doesn't find a match for the location "/auth/oidc/callback". Even though the documentations writes:

> All configured providers automatically register the following server routes.
> 
> /auth/<provider>/callback
> /auth/<provider>/login
> /auth/<provider>/logout

I have a minimum setup with no custom routes at all and "login" and "logout" are working perfectely. Just the the callback function that should be registered automatically gets the warning

> [Vue Router warn]: No match found for location with path "/auth/oidc/callback"

and the UI shows "500, callback failed, missing code).

Is there something special that one should now about the auto-registered OIDC fallback?

Thank you very much!

**Comment by itpropro** [comment]
Hi @the-tmp, could you please verify with the most current version?
The vue warning is fine btw, that appears, as it is a server route. Also always make sure that you use the provided composables for login/logout.
For further troubleshooting you nuxt config without sensitive information would be required.

**Comment by the-tmp** [comment]
Hi @itpropro 
I just updated to the latest version 0.15.1 and still have the same warning. It was strange for me that I get the warning just for the callback but not for the login and logout pages. After the update I have new issue but thisone seems just to be a OIDC configuration mistake of mine. I am new to Nuxt but I will try to double check everything next weekend and hopefully I can give you an update.
Thanks a lot!

**Comment by itpropro** [comment]
Hey @the-tmp 
If you share your config and which oidc provider you use, I can try to reproduce and help you get your problem solved.

**Comment by the-tmp** [comment]
Hello @itpropro 
I updated to v0.17.0. I am using the free Zitadel IAM cloud service as IDP and the following OIDC Config:

`  oidc: {
    defaultProvider: 'oidc',
    providers: {
      oidc: {
        clientId: '',
        clientSecret: '',
        authorizationUrl: 'https://xyz.zitadel.cloud/oauth/v2/authorize',
        tokenUrl: 'https://lxyz.zitadel.cloud/oauth/v2/token',
        redirectUri: 'http://localhost:3000/auth/oidc/callback',
        //grantType: 'authorization_code'
      }
    },
    middleware: {
      globalMiddlewareEnabled: true,
      customLoginPage: false
    }
  }`

I get the this warning now:

> [nuxt-oidc-auth]: { error: 'invalid_request', error_description: 'grant_type missing' }

The warning is still there, but I think the callback request is accepted by nuxt-oidc-auth (as you said I should ignore it) but when it tries to get the Token it seems to not send the required "grant_type=authorization_code". I tried to configure the grantType, even though it should be default according to the documenatation, but I got the same error.

I tested the Zitadel setup with the OAUTH Playground (https://www.oauth.com/playground/oidc.html) and it worked as intended. The IDP configuration should be ok.

I think we should switch with this to a new issue, as it seems that this is not about the callback issue anymore.

Thank you very much. I am sure, I just missed a little configuratio detail but I can't figure out with one.

best regards

**Comment by itpropro** [comment]
> Hello @itpropro I updated to v0.17.0. I am using the free Zitadel IAM cloud service as IDP and the following OIDC Config:
> 
> ` oidc: { defaultProvider: 'oidc', providers: { oidc: { clientId: '', clientSecret: '', authorizationUrl: 'https://xyz.zitadel.cloud/oauth/v2/authorize', tokenUrl: 'https://lxyz.zitadel.cloud/oauth/v2/token', redirectUri: 'http://localhost:3000/auth/oidc/callback', //grantType: 'authorization_code' } }, middleware: { globalMiddlewareEnabled: true, customLoginPage: false } }`
> 
> I get the this warning now:
> 
> > [nuxt-oidc-auth]: { error: 'invalid_request', error_description: 'grant_type missing' }
> 
> The warning is still there, but I think the callback request is accepted by nuxt-oidc-auth (as you said I should ignore it) but when it tries to get the Token it seems to not send the required "grant_type=authorization_code". I tried to configure the grantType, even though it should be default according to the documenatation, but I got the same error.
> 
> I tested the Zitadel setup with the OAUTH Playground (https://www.oauth.com/playground/oidc.html) and it worked as intended. The IDP configuration should be ok.
> 
> I think we should switch with this to a new issue, as it seems that this is not about the callback issue anymore.
> 
> Thank you very much. I am sure, I just missed a little configuratio detail but I can't figure out with one.
> 
> best regards

The problem was not the grant_type, but the type of format Zitadel expects. 
These are the important configurations to make Zitadel work:

```
        validateAccessToken: false,
        validateIdToken: true,
        skipAccessTokenParsing: true,
        tokenRequestType: 'form-urlencoded',
        scope: ['openid', 'offline_access'],
        authorizationUrl: 'https://PROJECT.us1.zitadel.cloud/oauth/v2/authorize',
        tokenUrl: 'https://PROJECT.us1.zitadel.cloud/oauth/v2/token',
        userInfoUrl: 'https://PROJECT.us1.zitadel.cloud/oidc/v1/userinfo',
        redirectUri: 'http://localhost:3000/auth/oidc/callback',
        logoutUrl: 'https://PROJECT.us1.zitadel.cloud/oidc/v1/end_session',
```

I created a dedicated provider for Zitadel that handles everything for you. This will be the config as soon as it releases today:

```
      zitadel: {
        clientId: '',
        clientSecret: '', // Works with PKCE and Code flow, just leave empty for PKCE
        redirectUri: 'http://localhost:3000/auth/zitadel/callback',
        baseUrl: '',
        audience: '', // Specify for id token validation, normally same as clientId
        logoutRedirectUri: 'https://google.com', // Needs to be registered in Zitadel portal
        authenticationScheme: 'none', // Set this to 'header' if Code is used instead of PKCE
      },
```

**Comment by the-tmp** [comment]
Hi @itpropro

Thank you very much. You saved me a lot of trail & error this weekend. I couldn't install the newest version yet but with your hints above it is working perfectly. I even don't get the missing callback warning any more... I haven't changed anything except added the token attributes in the config.

I will keep testing until I get the hang of it all a little better.

Thanks again!

best regards

**Comment by itpropro** [comment]
> Hi @itpropro
> 
> Thank you very much. You saved me a lot of trail & error this weekend. I couldn't install the newest version yet but with your hints above it is working perfectly. I even don't get the missing callback warning any more... I haven't changed anything except added the token attributes in the config.
> 
> I will keep testing until I get the hang of it all a little better.
> 
> Thanks again!
> 
> best regards

I just released the new version. It also handles some configurations that were necessary to get the logout redirection to work correctly.
Please test out the new provider and give some feedback on how that one works.

**Comment by the-tmp** [comment]
Hello @itpropro 
Thank you very much. I updated to the newest version, switched to Zitadel as provider and cleaned out my old config. Working perfectly! Do you wan't me to test anything special for you?
Best regards
