### ISSUE TITLE
Cannot use dev mode with Playwright against production container

### ISSUE THREAD

**Issue by Damien-VS** [itpropro/nuxt-oidc-auth#46]
Could be associated with #26 , underlying problem is not the same.

We use container promotion and environment variable injection. Our process looks like this :

1. build app
2. containerize
3. inject TEST .env properties in container & test with playwright
4. promote to dev -> inject DEV .env properties and run in the DEV cloud
5. promote to prod -> inject PROD .env properties and run in the PROD cloud

**Needs**:
- Be able to choose between OIDC / mock in local, test and DEV cloud environment
- Be able to set "NODE_ENV" to whatever value we need and still respect the point above
- Be able to switch OIDC/mock at cold start / runtime (not build time)
- Not have code suggesting an unexpected behavior (eg: "devMode.enabled: true" on prod environment with devMode disabled)

**Problems**: 
- nuxt.config.ts is executed at build time, and valid for all environment. Hence the flag "oidc.devMode.enabled=true" will be present everywhere (bad readability)
- process.env.NODE_ENV has to be "TEST" for some plugins, "E2E" for others and "development" for this plugin (bad reuse of not-owned property)

**Proposed solution**:
 - Get rid of the "oidc.devMode.enabled=true" that MAY NOT activate devMode
 - activate devMode on an owned env property. eg : "process.env.NUXT_OIDC_DEVMODE=true" or "process.env.NUXT_OIDC_MODE=mock"
 - stop mixing "dev" with "mock" as the two concepts are differents, albeit often used together. this is confusing on edge cases
 
 - BONUS : export [DevModeConfig](https://github.com/itpropro/nuxt-oidc-auth/blob/930b6d700bbc499583a78e564da33d8698af46f4/src/module.ts#L34) type to be imported in out `nuxt.config.ts`

**Comment by itpropro** [comment]
Thanks for the extensive feedback.
Dev mode by the name was introduced for local development and testing, not for automated testing or mocking. It is not possible to mock a oidc provider in a way that is sufficient for testing, as every IdP is different and no one confirms to the OIDC standard 100%.
We will adjust the config filter to

`!process.env.NODE_ENV.toLowerCase().startsWith('prod') && options.devMode?.enabled`

Removing even more limitations from dev mode would increase the chance for the user to accidentally introduce security issues.
I would recommend to try to either mock it (not a good solution) or better introduce a low overhead oidc server or better the one you will use in production into your testing environment. Especially for E2E tests, mocks should be avoided and from a DevSecOps perspective, I would recommend to always use the proper oidc identity provider starting in dev, which should be possible for self hosted IdPs like Keycloak as well as all public cloud IdPs. 

I am open to proposals or PR for a setup that supports automatic testing.
