### ISSUE TITLE
Logout using AzureStorageTable storage driver fails with 404

### ISSUE THREAD

**Issue by AbhishekKrishna123** [itpropro/nuxt-oidc-auth#47]
I have configured my Nuxt project to use persistent storage and I'm using the Azure Storage Table driver.
I am getting a 404 error while logging out that the Resource is not found.

![image](https://github.com/user-attachments/assets/32a46457-206b-448a-b89b-fd618403ccd1)

This is my Nuxt server config:
```
storage: {
  oidc: {
      driver: 'azureStorageTable',
      accountName: 'accname',
      tableName: 'oidcSessions'
    }
}
```

## What's happening?

I was able to reproduce the issue using just the Nitro storage and unstorage and found that it was happening because of the "removeMeta" option when used in conjunction with the Azure storage table driver.

On login, the item is added to the table storage as expected. While logging out, the item is first deleted but due to the `removeMeta` option, an additional delete is issued for 

**session.ts**
L55: `await useStorage('oidc').removeItem(session.id as string, { removeMeta: true })`

### Option 1: Fix unstorage library or the Azure storage table driver
This is the line in UnStorage which is responsible for this error.
https://github.com/unjs/unstorage/blob/badf993e8b9441901096d514f0c7dbd212574d90/src/storage.ts#L288

There is no flag for handling the exception thrown when `removeMeta` is set. This seems to be a larger issue with the unstorage implementation rather than being driver specific. This can be solved, but it's a more complex problem to solve than option 2 below.

### Option 2: Fix this module :)
I see that this module is not using the `setMeta()` function anywhere to set additional metadata. Hence it should not be necessary to use the `removeMeta` option and it can be removed from L55 in `session.ts`. This will fix the bug and should not have any feature regressions.

**Comment by itpropro** [comment]
Hi @AbhishekKrishna123 ,
you are right, `setMeta` is not necessary, it was taken from authUtils, where it was probably added, because of how some drivers in unstorage handle metadata.
I will remove it with the next version.

**Comment by AbhishekKrishna123** [comment]
@itpropro Thanks for confirming the issue. I have a PR #48 open for review. Thanks!
