### ISSUE TITLE
How to use with `@nuxtjs/i18n`

### ISSUE THREAD

**Issue by mrleblanc101** [itpropro/nuxt-oidc-auth#53]
Hi,
I use the keycloak provider and I'd like my login page to be `/` and `/en`
And I'd like my home page once logged to be `/tableau-de-bord` and `/en/dashboard`

**Comment by mrleblanc101** [comment]
Also, I would like to provide an additional `ui_locales=fr` or `ui_locales=en` params to keycloak so that it display in the same locale as the app.

**Comment by itpropro** [comment]
I added that in 0.14.0 as you already saw, for the initial problem, I think the easiest way would be to use `callbackRedirectUrl` and set it to a route with a custom middleware that handles the redirect.
You can set custom login page to true and handle the redirect based on the current locale there, as there is currently no option to set one (or event multiple) custom login routes, but that is something I will put into the backlog.

**Comment by itpropro** [comment]
@mrleblanc101 The next release will also contain an additional parameter for the logout composable to customize the redirect uri for providers that support a postRedirectUrl query string.

**Comment by mrleblanc101** [comment]
@itpropro But the login url is still `/auth/login` and there is no way to customize that because it's based on the filesystem.

**Comment by itpropro** [comment]
You are right, I will open a separate issue for that so that, as it is probably a little bit bigger change to make that customizable.
I hope the recent changes help at least a bit already.
