### ISSUE TITLE
Continuous redirects with Keycloak

### ISSUE THREAD

**Issue by sprijk** [itpropro/nuxt-oidc-auth#59]
nuxt-oidc-auth version: **0.17.0**
Nuxt version: **3.13.2**
Keycloak version: **25.0.6**

I created a new Nuxt app that runs on `http://localhost:3000`

I've created a Keycloak Client in a Keycloak Realm and added:
- Valid redirect URIs: `http://localhost:3000/*`
- Client authentication: On

From the Keycloak Admin Console I've obtained the  Client secret & id. The base URL is `https://<keycloak-host>/realms/<realm>`. These values are added in the `.env` file:
```bash
NUXT_OIDC_TOKEN_KEY='xxx'
NUXT_OIDC_SESSION_SECRET='xxx'
NUXT_OIDC_AUTH_SESSION_SECRET='xxx'
NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_SECRET='xxx'
NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_ID='local-dev'
NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL='https://<keycloak-host>/realms/<realm>'
```

Noticeable is that the Keycloak server runs on a public https domain.

With adding the `oidc` block in `nuxt.config.ts`
```ts
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  modules: ['nuxt-oidc-auth'],
  oidc: {
    defaultProvider: 'keycloak',
    providers: {
      keycloak: {
        clientSecret: 'xxx',
        clientId: 'xxx',
        baseUrl: 'xxx',
      },
    },
  },
})
```
the editor complains (due to types in `node_modules/nuxt-oidc-auth/dist/module.d.ts`) that a `redirectUri` is required in the `oidc.providers.keycloak` block.

I'm not sure what this should be, so I'll use `http://localhost:3000`

Adding this results in:
```ts
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  modules: ['nuxt-oidc-auth'],
  oidc: {
    defaultProvider: 'keycloak',
    providers: {
      keycloak: {
        clientSecret: 'xxx',
        clientId: 'xxx',
        baseUrl: 'xxx',
        redirectUri: 'http://localhost:3000',
      },
    },
  },
})
```

Now, when starting the application (`npm run dev`), the page (at `http://localhost:3000`) takes me to the login of the realm successfuly.

After giving the credentials and hitting the "Sign In" button, the browser infinitely redirect me back and forth between `http://localhost:3000` and`https://<keycloak-host>/realms/<realm>/protocol/openid-connect/auth?client_id=local-dev&response_type=code&scope=openid&redirect_uri=http:%2F%2Flocalhost:3000&code_challenge=xxx&code_challenge_method=S256&response_mode=form_post&nonce=xxx`

This repeats infinitely.

Is this a known issue, or is it clear what is wrongly configured?

Any pointers are highly appreciated, thanks in advance!

**Comment by sprijk** [comment]
The same happens when testing this setup with a Keycloak instance running locally in Docker.

Steps to reproduce:

**1. Setup Keycloak**

- Start Keycloak using this `docker-compose.yaml` file:
```
services:
  keycloak:
    restart: unless-stopped
    image: quay.io/keycloak/keycloak
    command: start-dev
    ports:
      - "8888:8080"
      - "9999:9000"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
```
- Create a realm
- Create a user
- Create a client (use "Valid redirect URIs": `http://localhost:3000/*` and "Client authentication": `On`)
- Obtain the client ID and secret from the "Credentials" tab


**2. Setup Nuxt**
- `npx nuxi@latest init test`
- `cd test`
- `npx nuxi@latest module add nuxt-oidc-auth`
- Add the `oidc` config block in `nuxt.config.ts`
```
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  modules: ['nuxt-oidc-auth'],
  oidc: {
    defaultProvider: 'keycloak',
    providers: {
      keycloak: {
        clientSecret: '<client secret>',
        clientId: '<client id>',
        baseUrl: 'http://localhost:8888/realms/<realm>',
        redirectUri: 'http://localhost:3000',
      },
    },
  },
})
```
- `npm i`
- Create a `pages/index.vue`
```html
<template>
  <div>
    <h1>Home Page</h1>
  </div>
</template>
```

**3. Run**
- `npm run dev`
- Navigate to [http://localhost:3000](http://localhost:3000)
- You will get redirected to Keycloak
- Sign in as the user
- Observe the redirects

**Comment by itpropro** [comment]
> The same happens when testing this setup with a Keycloak instance running locally in Docker.
> 
> Steps to reproduce:
> 
> **1. Setup Keycloak**
> 
> * Start Keycloak using this `docker-compose.yaml` file:
> 
> ```
> services:
>   keycloak:
>     restart: unless-stopped
>     image: quay.io/keycloak/keycloak
>     command: start-dev
>     ports:
>       - "8888:8080"
>       - "9999:9000"
>     environment:
>       KEYCLOAK_ADMIN: admin
>       KEYCLOAK_ADMIN_PASSWORD: admin
> ```
> 
> * Create a realm
> * Create a user
> * Create a client (use "Valid redirect URIs": `http://localhost:3000/*` and "Client authentication": `On`)
> * Obtain the client ID and secret from the "Credentials" tab
> 
> **2. Setup Nuxt**
> 
> * `npx nuxi@latest init test`
> * `cd test`
> * `npx nuxi@latest module add nuxt-oidc-auth`
> * Add the `oidc` config block in `nuxt.config.ts`
> 
> ```
> export default defineNuxtConfig({
>   compatibilityDate: '2024-04-03',
>   devtools: { enabled: true },
>   modules: ['nuxt-oidc-auth'],
>   oidc: {
>     defaultProvider: 'keycloak',
>     providers: {
>       keycloak: {
>         clientSecret: '<client secret>',
>         clientId: '<client id>',
>         baseUrl: 'http://localhost:8888/realms/<realm>',
>         redirectUri: 'http://localhost:3000',
>       },
>     },
>   },
> })
> ```
> 
> * `npm i`
> * Create a `pages/index.vue`
> 
> ```
> <template>
>   <div>
>     <h1>Home Page</h1>
>   </div>
> </template>
> ```
> 
> **3. Run**
> 
> * `npm run dev`
> * Navigate to http://localhost:3000
> * You will get redirected to Keycloak
> * Sign in as the user
> * Observe the redirects

I cannot reproduce that. I set up keycloak with your docker file, configured redirect uris and client auth with secret on a new realm and it just works.
Here is my nuxt.config:

```
      keycloak: {
        audience: 'account',
        baseUrl: 'http://localhost:8080/realms/nuxt-oidc-test',
        clientId: 'ea060477-78cf-4a45-858d-2c32155fdffa',
        clientSecret: 'SECRET',
        redirectUri: 'http://localhost:3000/auth/keycloak/callback',
        userNameClaim: 'preferred_username',
      },
```

**Comment by sprijk** [comment]
Ok, clear! That was it, complete works now as expected 💯

Apologies for bothering you on such a simple misconfiguration...!

I'm not using the attributes `audience` and `userNameClaim` at the moment. 
I'll research what they're for.

**Comment by itpropro** [comment]
> Ok, clear! That was it, complete works now as expected 💯
> 
> Apologies for bothering you on such a simple misconfiguration...!
> 
> I'm not using the attributes `audience` and `userNameClaim` at the moment. I'll research what they're for.

Hey,
no problem! I added a part to the docs to better clarify what the redirectUri is used for. 
I think it is time to create a dedicated docs site, it kind of exploded a little...

**Comment by sprijk** [comment]
Haha ok. Well good luck!
