### ISSUE TITLE
How to run tests with OIDC auth enabled?

### ISSUE THREAD

**Issue by ekarlso** [itpropro/nuxt-oidc-auth#61]
Hi, do you have a example running browser tests with the oidc enabled? For me it gives the following when OIDC auth is enabled in tests

```
tui:test:  FAIL  tests/index-page.spec.ts > basic index page test
tui:test: TypeError: The "chunk" argument must be of type string or an instance of Buffer or Uint8Array. Received undefined
tui:test:  ❯ _build ../../node_modules/.pnpm/nitropack@2.9.7_encoding@0.1.13_magicast@0.3.5_webpack-sources@3.2.3/node_modules/nitropack/dist/nitro.mjs:2658:22
tui:test:  ❯ ../../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@20.11.24_encoding@0.1.13_eslint@9.11.1_jiti@1.2_d3332nrp3hsrobhivvuowxqlqm/node_modules/nuxt/dist/index.mjs:3630:5
tui:test:  ❯ build ../../node_modules/.pnpm/nuxt@3.13.2_@parcel+watcher@2.4.1_@types+node@20.11.24_encoding@0.1.13_eslint@9.11.1_jiti@1.2_d3332nrp3hsrobhivvuowxqlqm/node_modules/nuxt/dist/index.mjs:5778:3
tui:test:  ❯ buildFixture ../../node_modules/.pnpm/@nuxt+test-utils@3.14.2_@testing-library+vue@8.1.0_@vue+compiler-sfc@3.5.10_vue@3.5.10_typesc_5j7nmah2w5go4jkqtie3un2u3q/node_modules/@nuxt/test-utils/dist/shared/test-utils.CaqvQLs_.mjs:121:3
tui:test:     119|   const { After, AfterAll, Before, BeforeAll } = await import('@cucumber/cucumber');
tui:test:     120|   BeforeAll({ timeout: hooks.ctx.options.setupTimeout }, hooks.setup);
tui:test:     121|   Before(hooks.beforeEach);
tui:test:        |   ^
tui:test:     122|   After(hooks.afterEach);
tui:test:     123|   AfterAll(hooks.afterAll);
tui:test:  ❯ setup2 ../../node_modules/.pnpm/@nuxt+test-utils@3.14.2_@testing-library+vue@8.1.0_@vue+compiler-sfc@3.5.10_vue@3.5.10_typesc_5j7nmah2w5go4jkqtie3un2u3q/node_modules/@nuxt/test-utils/dist/shared/test-utils.CaqvQLs_.mjs:183:7
tui:test: 
tui:test: ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯[1/1]⎯
```

**Comment by itpropro** [comment]
I don't think it is related to nuxt-oidc-auth, there is at least nothing in the log that indicates that. E2E tests works normally as with every other Nuxt app as long as you have configured a valid identity provider and you redirects are ok.

**Comment by ekarlso** [comment]
Ah, so I would require to have a working IDP when running the tests then ? :thinking:

**Comment by itpropro** [comment]
If you are running E2E tests, that would be best practice. The dev mode is only for local development and not for testing. If you are making actual user flow tests that include authentication, it should use a test instance of your production IDP.
It would theoretically be possible to craft a session state manually, store it encrypted in the storage location and inject a static cookie at test time that has the mapped session id, but I would not really recommend that currently, besides from being quite complex.

**Comment by itpropro** [comment]
If you are just doing component test etc. in a closed testing environment, think about just disabling the module via injected config. But always use config injection, never hardcode any configuration to make sure that you are not shipping disabled components to production.
