### ISSUE TITLE
Zitadel - be able to run with localhost:8080 / local instance during development

### ISSUE THREAD

**Issue by ekarlso** [itpropro/nuxt-oidc-auth#64]
Would it be possible to support this when running say in development?

**Comment by itpropro** [comment]
Just change the redirect uri in the config and in the Zitadel UI.

**Comment by ekarlso** [comment]
Doesn't work currently because nuxt-oidc requires https:// and by default in the compose setup Zitadel uses http on :8080

**Comment by itpropro** [comment]
You can just change it in the config there is no https requirement:
![image](https://github.com/user-attachments/assets/7d24f40c-82b9-429f-8371-cb4db4934821)
![image](https://github.com/user-attachments/assets/55069a50-763c-4936-aa35-68c5f1e952ad)
Just tested:
![image](https://github.com/user-attachments/assets/34f1a27f-8735-43a5-bd21-60427bf8ce6d)

**Comment by ekarlso** [comment]
Hi, yeah but that not gonna work locally due to https://github.com/itpropro/nuxt-oidc-auth/blob/main/src/runtime/providers/zitadel.ts#L39 no ?

**Comment by itpropro** [comment]
My screenshot is from my local machine in http ;)
The line you are referencing is just making sure that if you use token validation (which is only used when the audience is set correctly, it is turned on and it is possible to resolve the openid config) that the well-known config of the provides (Zitadel in our case) is requested from a https url.

**Comment by ekarlso** [comment]
Ah, ok thank you!

Am I assuming btw that I should be able to enable Zitadel config purely via ENV vars like having a empty 
```
  oidc: {
    session: {
      // expirationCheck: true,
      automaticRefresh: true,
      expirationThreshold: 3600,
    },
    middleware: {
      globalMiddlewareEnabled: true,
      customLoginPage: false,
    },
    providers: {}
  },
```

and then providing the following in my .env or in a production built deployment?

```shell
NUXT_OIDC_PROVIDERS_ZITADEL_CLIENT_ID=282949336457872899@tradero
NUXT_OIDC_PROVIDERS_ZITADEL_CLIENT_SECRET=""
# NUXT_OIDC_PROVIDERS_ZITADEL_AUDIENCE=282949336457872899@tradero
NUXT_OIDC_PROVIDERS_ZITADEL_BASE_URL=http://localhost:8080
NUXT_OIDC_PROVIDERS_ZITADEL_REDIRECT_URI=http://localhost:3000/auth/zitadel/callback
NUXT_OIDC_PROVIDERS_ZITADEL_LOGOUT_REDIRECT_URI=http://google.com
NUXT_OIDC_PROVIDERS_ZITADEL_AUTHENTICATION_SCHEME=none
```

**Comment by itpropro** [comment]
The way how nuxt work you still have to have all of the entries that you want to set via env variables in your nuxt.config.ts as empty strings, but the rest is correct.

**Comment by ekarlso** [comment]
Well then that is weird with what you say about `audience` because I don't have it set.

**Comment by itpropro** [comment]
> Well then that is weird with what you say about `audience` because I don't have it set.

If the clientId or the audience field is in the `aud` claim or the accessToken or idToken, token validation takes place. Zitadel doesn't hand out parseable accessTokens by default, so the accessToken is definitely not validated. The idToken is then validated, if the `aud` field of the idToken matches clientId or audience config if set.
So the only token that could be validated is the idToken.

**Comment by itpropro** [comment]
I would close this issue for now, if you have a separate question or another issue feel free to open a new one for that.
