### ISSUE TITLE
config.openIdConfiguration is not a function

### ISSUE THREAD

**Issue by DiogoCunhaMoreira** [itpropro/nuxt-oidc-auth#65]
Hello guys,

I need to make the skipAccessTokenParsing false so i can have my session maxAge equal to the expireAt of the token. 

When i do this i get the error config.openIdConfiguration is not a function in the /runtime/server/lib/oidc.ts:214:1, dont understand what is causing this, i just know that config is just a variable containing my oidc provider configurations.

Any clue about this?

Thanks,
Diogo

**Comment by itpropro** [comment]
Hey,
Which provider are you using, can you please share your package version and nuxt.config.ts?

**Comment by DiogoCunhaMoreira** [comment]
Hello!

I'm using the v0.17.0.

The provider i'm using an external oidc provider (ping identity).

My nuxt.config.ts:

<img width="425" alt="image" src="https://github.com/user-attachments/assets/e66c80ff-c156-4468-ac58-4a1ea52decd5">

Anything else please feel free to ask!
Thanks a lot

**Comment by christianOB** [comment]
When I had this issue using a custom oidc, I had to point `openIdConfiguration` to the path of my OpenID provider configuration endpoint so in the providers oidc config I did this: 
```
// @ts-expect-error
openIdConfiguration: 'http://localhost:3001/oidc/.well-known/openid-configuration',
```
Your URL will be different and  I believe the error comes from this line: https://github.com/itpropro/nuxt-oidc-auth/blob/e79f8565515e81826af48a3eca44d61018861cc1/src/runtime/server/handler/callback.ts#L129

Alternatively, you can set `validateAccessToken` and `validateIdToken`, which should bypass the code.

**Comment by itpropro** [comment]
> When I had this issue using a custom oidc, I had to point `openIdConfiguration` to the path of my OpenID provider configuration endpoint so in the providers oidc config I did this:
> 
> ```
> // @ts-expect-error
> openIdConfiguration: 'http://localhost:3001/oidc/.well-known/openid-configuration',
> ```
> 
> Your URL will be different and I believe the error comes from this line:
> 
> https://github.com/itpropro/nuxt-oidc-auth/blob/e79f8565515e81826af48a3eca44d61018861cc1/src/runtime/server/handler/callback.ts#L129
> 
> Alternatively, I believe you can set `validateAccessToken` and `validateIdToken` to false, which should bypass the code.

We don't need to bypass that code, as it checks if you provided a string and then uses the string as the url for the fetch call.
Please try to use 0.18.0, I am not sure if 0.17.0 was already checking for string input.
I would try to get token validation to work (if your IdP provides parseable and validateable strings of course) as it provides higher security, especially in enterprise scenarios.

**Comment by DiogoCunhaMoreira** [comment]
Hello guys,

So i have now the 0.18.0 and after changing the code to include a proxy in the ofetch call (i need to do this because my company dont allow requests without a proxy configured) and also configuring the openIdConfiguration in the nuxt.config now i get the error "Token validation failded: TypeError: Invalid URL code: 500. " 
Don't understand it because the url .../.wellknown/openid_configuration works when using the browser.

Can't see in the error the callstack but i presume the error is here (callback.ts):

![image](https://github.com/user-attachments/assets/42539579-1142-4c1c-a096-f414d266b4cb)

Did this also hapen to anyone?

Thanks,
Diogo

**Comment by TonyArntsen** [comment]
> Hello guys,
> 
> So i have now the 0.18.0 and after changing the code to include a proxy in the ofetch call (i need to do this because my company dont allow requests without a proxy configured) and also configuring the openIdConfiguration in the nuxt.config now i get the error "Token validation failded: TypeError: Invalid URL code: 500. " Don't understand it because the url .../.wellknown/openid_configuration works when using the browser.
> 
> Can't see in the error the callstack but i presume the error is here (callback.ts):
> 
> ![image](https://private-user-images.githubusercontent.com/60873246/374572585-42539579-1142-4c1c-a096-f414d266b4cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTQ3NjQsIm5iZiI6MTcyODM5NDQ2NCwicGF0aCI6Ii82MDg3MzI0Ni8zNzQ1NzI1ODUtNDI1Mzk1NzktMTE0Mi00YzFjLWEwOTYtZjQxNGQyNjZiNGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDEzMzQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwNmEwYjU4MjcxMjJlZjZmMTMwYTA1MzA3ZGYxN2M3ODg1OGMxODk4YThmNWUwYTg0YTUyOGU2NTg0MmQxYmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DzmkB2TG2HsqL1slXUZ2q8EUxv1AIybo11kYoyR2F2Y)
> 
> Did this also hapen to anyone?
> 
> Thanks, Diogo

I am facing the same problems.

**Comment by itpropro** [comment]
> Hello guys,
> 
> So i have now the 0.18.0 and after changing the code to include a proxy in the ofetch call (i need to do this because my company dont allow requests without a proxy configured) and also configuring the openIdConfiguration in the nuxt.config now i get the error "Token validation failded: TypeError: Invalid URL code: 500. " Don't understand it because the url .../.wellknown/openid_configuration works when using the browser.
> 
> Can't see in the error the callstack but i presume the error is here (callback.ts):
> 
> ![image](https://private-user-images.githubusercontent.com/60873246/374572585-42539579-1142-4c1c-a096-f414d266b4cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzOTk2OTEsIm5iZiI6MTcyODM5OTM5MSwicGF0aCI6Ii82MDg3MzI0Ni8zNzQ1NzI1ODUtNDI1Mzk1NzktMTE0Mi00YzFjLWEwOTYtZjQxNGQyNjZiNGNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDE0NTYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NjQ1NzQ3NTMwOTg0YWU0ODRiYTYxOTNkMzYyMGU4YzNiZTI5ZjA1NzljMTg5NDJkYjVlZDA4MDMwNWVjYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ww1thahRN0X26qvhwIKxXUM6iHF6LNz2yY6tQn-E7yE)
> 
> Did this also hapen to anyone?
> 
> Thanks, Diogo

Can you please create a new issue for that and share the exact error from the console, so it can be reproduced? Thanks!
