### ISSUE TITLE
[Keycloak] Logout redirect stopped working after 0.17.0

### ISSUE THREAD

**Issue by mrleblanc101** [itpropro/nuxt-oidc-auth#68]
When using Keycloak, after upgrading from `0.17.0` to `0.18.0` or `1.0.0-beta.1` I am not being redirected after the logout.
The parameter `logoutRedirectParameterName: 'post_logout_redirect_uri',` is missing from the URL:

http://eeq-sso.local.vici.io/realms/symbioos/protocol/openid-connect/logout?id_token_hint=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJnQkNVNXlCS1hwb3dyLTVSTmpMQk9wbkJsWFM3aWNaam0xcjRSckxSU0JzIn0.eyJleHAiOjE3MjgzMjQ3MzQsImlhdCI6MTcyODMyNDEzNCwiYXV0aF90aW1lIjoxNzI4MzI0MTM0LCJqdGkiOiJiOGY5NDYyZC0xMjdjLTQ4ZjAtODkyYS02NmQ4YjczYjIzMGIiLCJpc3MiOiJodHRwOi8vZWVxLXNzby5sb2NhbC52aWNpLmlvL3JlYWxtcy9zeW1iaW9vcyIsImF1ZCI6ImNhbXB1cy12aXJ0dWVsLXZ1ZWpzIiwic3ViIjoiNWE0NDYxM2UtMmExYS00ZjI1LThlMjYtNzJhYmEzN2ZlMGU2IiwidHlwIjoiSUQiLCJhenAiOiJjYW1wdXMtdmlydHVlbC12dWVqcyIsIm5vbmNlIjoiczlUeGFYY0xUS3NpcFdrVlRFYVBqQTU3NnpTUTZxQ1FTU0tZSlpWRjVEd2RIQW9YIiwic2lkIjoiYjMwOWJjYmQtMDViMy00NTU0LWJkNjQtZDJkOGJkMDQzMjUyIiwiYXRfaGFzaCI6IjFnaFU0ckRrSWdhN3VKLXNMck5BamciLCJhY3IiOiIxIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJNYXRoaWV1IFNhdmFnZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImVlcV9kZXZfdXNlcjFAcWEubGliZW8uY29tIiwiZ2l2ZW5fbmFtZSI6Ik1hdGhpZXUiLCJsb2NhbGUiOiJmciIsImZhbWlseV9uYW1lIjoiU2F2YWdlIiwiZW1haWwiOiJlZXFfZGV2X3VzZXIxQHFhLmxpYmVvLmNvbSJ9.ANz6yNMUdycdJD7FRkeAE6cb6Ky9n9JLWOzt76GsI9PpRtQ31zCG2KltUjtkSHDBYS7abs8vxzLhXc8zAa7xhNLodMLrjwfVa1bTfwhikabNPZPrvDjI3fC81TybRIKiaLIc6vG-mt3cyBRIHIQAex4-p5vrRyecyIwaDpX_KYoqCNwBKXYYSkll3O9QKs_4XmO0uJlkj4frPvmhR737N0_wsQ5xBHlq46GjNIYnCKNfxMPMzx6MndLxBhG-Yu5l_ZMQadGXQ83UK_807QhXGmMHRVZh5WTDO9R9uZZpd4ofJq83IHxehPJXJzYh60NmD0REtriU1ovMAGIOpSMaaQ

![Screenshot 2024-10-07 at 1 55 07 PM](https://github.com/user-attachments/assets/93c3b1e3-30ab-42a0-a9b0-92937a77f173)

**Comment by itpropro** [comment]
The `logoutRedirectParameterName` content is only appended, if you have defined a `logoutRedirectUri`. Do you have that one set?
Before 0.18.0, it was appended anyway, which lead to problems with multiple providers. As the `logoutRedirectUri` contains the content of the field defined by `logoutRedirectParameterName`, it wouldn't make sense to append it, if `logoutRedirectUri` isn't set.
Also, the `logoutRedirectUri` is normally has to be allowed and configured at the IdP, this is where that is in my KeyCloak
![image](https://github.com/user-attachments/assets/2c8251c5-9144-4492-9f15-4430646fe00b)

I just tested the KeyCloak provider with this config with the current version:

nuxt.config.ts
```
keycloak: {
  audience: 'account',
  baseUrl: '',
  clientId: '',
  clientSecret: '',
  redirectUri: 'http://localhost:3000/auth/keycloak/callback',
  userNameClaim: 'preferred_username',
  logoutRedirectUri: 'http://localhost:3000',
},
```
.env
```
# KEYCLOAK ID PROVIDER CONFIG
NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_SECRET=SECRET
NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_ID=ID
NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL=http://localhost:8080/realms/nuxt-oidc-test
```

I hope this helps, I will definitely add that to the documentation as an example for KeyCloak so it is clear that the `logoutRedirectUri` has to be used.

**Comment by mrleblanc101** [comment]
Oh, it wasn't set but it worked in `0.17.0` and why looking it the changelog I didn't see anything about this.

The documentation explicitly stated that if omitted it would redirect to the homepage. This should indeed be clarified in the documentation, and maybe also added to the changelog.

Thanks 😊 

PS: I noticed that in the documentation, you alternate between `Keycloak` and `KeyCloak`. The former is the correct name.

**Comment by itpropro** [comment]
> Oh, it wasn't set but it worked in `0.17.0` and why looking it the changelog I didn't see anything about this.
> 
> The documentation explicitly stated that if omitted it would redirect to the homepage. This should indeed be clarified in the documentation, and maybe also added to the changelog.
> 
> Thanks 😊
> 
> PS: I noticed that in the documentation, you alternate between `Keycloak` and `KeyCloak`. The former is the correct name.

Thanks for the hints, I hope the config works for you now. I will update the docs asap.
