### ISSUE TITLE
Configuration not working in docker across different environments

### ISSUE THREAD

**Issue by TonyArntsen** [itpropro/nuxt-oidc-auth#71]
When using docker, it's not possible to configure the nuxt-oidc-auth module in different environments such as development/testing/production. This is because Nuxt relies on a .env file in my local environment, but environment variables are set in other ways during the deployment pipelines.

This has never been a problem for other kinds of env variables which are accessed through the runTimeConfig and used in plugins/components etc. But that wont work in this case.
Because the oidc auth config in nuxt.config.ts needs to read them directly though process.env, which seems to ONLY work when having a .env file. _(But according to Nuxt documentation, the .env file is ignored in production builds.)_

Example nuxt.config.ts:
`  oidc: {
    defaultProvider: "oidc",
    providers: {
      oidc: {
        clientId: process.env.NUXT_CLIENT_ID,
        clientSecret: process.env.NUXT_CLIENT_SECRET,
        authorizationUrl: process.env.NUXT_AUTH_URL,`
        

After running the container, this commands shows all env variables present and has values:
**docker-compose exec nuxt-app env**

But the auth module wasn't able to read them, it just shows url params such as client id being empty when the middleware attempts to do auth things. It's the exact same behaviour as if I had supplied empty values in the oidc config.

I suppose it's more of a nuxt + env vars issue, but perhaps there is simply no way to make this work, and therefore nuxt-oidc-auth needs a way to support it? If it is supported, there exists no documentation for this kind of setup. It would be really helpful for anyone attempting to do the same thing. I noticed that setting the NUXT_OIDC_AUTH_SESSION_SECRET works, which is read by the module itself.

**Comment by TonyArntsen** [comment]
I finally figured it out. Parts of the oidc config needs to be in runtimeconfig:

```
  runtimeConfig: {
    oidc: {
      providers: {
        oidc: {
          clientId: "",
          clientSecret: "",
          authorizationUrl: "",
          tokenUrl: "",
          userinfoUrl: "",
          redirectUri: "",
        },
      },
      middleware: {
        globalMiddlewareEnabled: true,
        customLoginPage: false
      },
      enabled: true,
      session: {}
    },
```

Your env vars much match this structure:
NUXT_OIDC_PROVIDERS_OIDC_CLIENT_ID

Due to some mechanism it will be populated in runtime. Now you can have multiple environments and not rely on a .env file.

**Comment by enmust** [comment]
Basically had the similar issue, locally everything worked fine, docker build/run "muah" like a charm. 
As soon it hit our production flow where everything was set during runtime it stopped working. 

What I found out that at least NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL needs to be set during build time. Unfortunately I couldn't find any information about it in the docs
