### ISSUE TITLE
Auth0 token fetch error after login missing grant_type

### ISSUE THREAD

**Issue by peirix** [itpropro/nuxt-oidc-auth#8]
I'm trying to set this up with an external openid library. I've managed to get everything working when using Postman to fetch token and userinfo, but transferring those details to nuxt is giving me some issues. Right now I'm able to be redirected to the external site for login, and then when returning to my localhost site, I get the 500 Token request failed error page. And in the logs I get this message:

```log
[nuxt-oidc-auth]: {
  error: 'invalid_request',
  error_description: 'Message does not include required parameter [grant_type]',
  error_uri: 'https://docs.dataporten.no'
}
```

Just for the sake of trying, I've taken the access code that is the url, and run that though Postman with the grant type set, but then I get `Code could not be PKCE verified` which is probably because I'm missing the verifier code. I've tried using any of the three I set up in my env file, but I just get `Provided Authorization Code was not found`.

```env
NUXT_OIDC_TOKEN_KEY=11eb4c069448a753ba21597a4b09fd9f2b3eefee05c17139d4fefc3d8a8e98b7
NUXT_OIDC_SESSION_SECRET=KV5ui0TYchqfC75dnmWdYV14rTZkapfP1xUKgHUJPxfQqtVg
NUXT_OIDC_AUTH_SESSION_SECRET=kTw1d79dWPhYM4w2LLNN32X8GPX2LnW1XmyrW2QppXt0P9Qi
```

Any suggestions on what I can check/change to make this work?

**Comment by peirix** [comment]
Okay, I realized that I had been setting it up using Auth0, and I'm not sure if the external site handles that, so I switched to generic oidc, and now my error message is `invalid JWT token` Is there a way for me to see what the response is somewhere?

**Comment by itpropro** [comment]
Hi @peirix,
have you set the settings according to the documentation (Depending on the settings of your apps Credentials tab, set authenticationScheme to body for 'Client Secret (Post)', set to header for 'Client Secret (Basic)', set to '' for 'None')?
If yes, could you provide the config of your Auth0 application so I can try to reproduce the issue?
Thanks!

**Comment by peirix** [comment]
Just wanted to comment that this is being followed up by my colleague in #9 so this can be closed.
