### ISSUE TITLE
Infinite loop on callback redirect with keycloak provider - [nitro] [unhandledRejection] Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by Wasabi-sudo** [itpropro/nuxt-oidc-auth#86]
### ENVIRONNEMENT                                                                                                                                    
Nuxt project info:                                                                                                                                                                                                    
------------------------------
- Operating System: Windows
- Node Version:     v20.17.0
- Nuxt Version:     3.13.2
- CLI Version:      3.15.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.8.3
- Builder:          -
- User Config:      default
- Runtime Modules:  nuxt-oidc-auth@0.18.0
- Build Modules:    -
------------------------------

### REPRODUCTION
Tree pages .vue
```
pages
  |_auth
    |_keycloak
      |_callback.vue
      |_ user.vue
      |_admin.vue
```
_Configuration nuxt.config.ts_
```
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  pages: true,
  modules: [
    'nuxt-oidc-auth'
  ],
  oidc: {
    defaultProvider: 'keycloak',
    providers: {
      keycloak: {
        audience: 'account',
        clientId: 'my-nuxt-oidc-auth',
        clientSecret: '***',
        redirectUri: 'http://localhost:3000/auth/keycloak/callback',
        baseUrl: 'https://.../realms/test',
        logoutUrl: 'https://.../realms/test/protocol/openid-connect/logout',
        logoutRedirectUri: 'http://localhost:3000/',
        userInfoUrl: 'https://.../realms/test/protocol/openid-connect/userinfo',
        authorizationUrl: 'https://.../realms/test/protocol/openid-connect/auth',
        tokenUrl: 'https://.../realms/test/protocol/openid-connect/token',
      }
    },
    middleware: {
      globalMiddlewareEnabled: true,
      customLoginPage: false
    }
  }
})
```

### BUG DESCRIPTION
After be authenticated with keycloak login and get tokens. The oidc session doesn't look correctly instantiate in my callback redirection " ERROR  [nitro] [unhandledRejection] Cannot set headers after they are sent to the client" (cf logs). And loop between these 4 calls

200 GET - https://../realms/test/protocol/openid-connect/auth?client_id=my-nuxt-oidc-auth&response_type=code&scope=openid&redirect_uri=http://localhost:3000/auth/keycloak/callback&code_challenge=***&code_challenge_method=S256&response_mode=form_post&nonce=*** 

302 POST - http://localhost:3000/auth/keycloak/callback

302 POST - http://localhost:3000/

302 POST - http://localhost:3000/auth/login

### LOGS

Infinite loop on this logs : 

[nuxt-oidc-auth]  ERROR  [nuxt-oidc-auth]: [POST] "https://.../realms/test/protocol/openid-connect/token": <no response> fetch failed

  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async $fetch2 (/C:/.../my-nuxt-oidc-auth/node_modules/ofetch/dist/shared/ofetch.03887fc3.mjs:316:15)
  at async Object.handler (node_modules\nuxt-oidc-auth\dist\runtime\server\lib\oidc.js:125:23)
  at async /C:/.../my-nuxt-oidc-auth/node_modules/h3/dist/index.mjs:1978:19
  at async Object.callAsync (/C:/.../my-nuxt-oidc-auth/node_modules/unctx/dist/index.mjs:72:16)
  at async Server.toNodeHandle (/C:/.../my-nuxt-oidc-auth/node_modules/h3/dist/index.mjs:2270:7)

[nuxt-oidc-auth]  ERROR  [nuxt-oidc-auth]: Token request failed code: 500

 ERROR  [nitro] [unhandledRejection] Cannot set headers after they are sent to the client

  at ServerResponse.setHeader (node:_http_outgoing:659:11)
  at setCookie (/C:/.../my-nuxt-oidc-auth/node_modules/h3/dist/index.mjs:612:18)
  at updateSession (/C:/.../my-nuxt-oidc-auth/node_modules/h3/dist/index.mjs:1384:5)
  at async getSession (/C:/.../my-nuxt-oidc-auth/node_modules/h3/dist/index.mjs:1369:5)
  at async useSession (/C:/.../my-nuxt-oidc-auth/node_modules/h3/dist/index.mjs:1311:3)
  at async clearUserSession (node_modules\nuxt-oidc-auth\dist\runtime\server\utils\session.js:18:19)

**Comment by 1v33n** [comment]
@Wasabi-sudo Have you found any solution? Currently facing the same problem with custom oidc-provider
