### ISSUE TITLE
Client-only authentication & sessions

### ISSUE THREAD

**Issue by mishu-** [itpropro/nuxt-oidc-auth#87]
Hi! Is there any way to make `nuxt-oidc-auth` work client side only? I think this means all the callback JWT token parsing should be available client side and use localStorage instead of nitro's storage?
This is the only nuxt OIDC library that implements PKCE and it seems that you cannot use it with your own APIs and OIDC providers without using nitro.
Maybe it's doable and I am missing something.

**Comment by Velka-DEV** [comment]
> This module only works with SSR (server-side rendering) enabled as it uses server API routes. You cannot use this module with nuxt generate or ssr turned off. We are currently investigating if and how to support prerendering.

https://nuxtoidc.cloud/getting-started/security#nuxt

**Comment by itpropro** [comment]
Hi,
This is not planned as this library is focused on the highest security and compliance with OIDC, which recommends a trusted client scenario, meaning a server side implementation.
